import Foundation

/// Detects project-**local** build/cache directories (`.cache`, `dist`, `target`, …) inside
/// user-configured project root paths. Dependency trees (`node_modules`, `.venv`) are never reclaimable.
///
/// Roots are stored in `ProjectScanPathStore`. When no roots are configured the rule
/// returns an empty findings list without walking the filesystem.
///
/// Walk strategy:
///   - Descend up to 5 levels below each root.
///   - Treat a directory as a finding when its last component matches a **local** artifact name
///     (not dependency trees like `node_modules` / `.venv`).
///   - Prune descent into dependency dirs without counting them as reclaimable.
///   - Apply a 7-day age gate (`ScanPolicy.defaultMinimumAgeSeconds(for: .projectArtifacts)`).
public struct ProjectArtifactRule: ScanRule {
    public let id = "project-artifacts"
    public let title = "Project Local Build Caches"
    public let reason = "Project-local build/tool cache (regenerated by build tools; not dependency trees)"
    public let category: ScanCategory = .projectArtifacts
    public let riskLevel: RiskLevel = .safe
    public let confidence: Double = 0.93

    private let pathStore: ProjectScanPathStore

    public init(pathStore: ProjectScanPathStore = .shared) {
        self.pathStore = pathStore
    }

    public func targetDirectories(environment: ScanEnvironment) -> [URL] { [] }
    public func include(fileURL: URL, resourceValues: URLResourceValues) -> Bool { false }

    public func customScan(environment: ScanEnvironment) async -> [ScanFinding]? {
        let roots = pathStore.paths
        guard !roots.isEmpty else { return [] }

        let minAge = ScanPolicy.defaultMinimumAgeSeconds(for: category)
        var findings: [ScanFinding] = []

        for root in roots {
            if Task.isCancelled { break }
            let rootURL = URL(fileURLWithPath: root)
            await walk(directory: rootURL, depth: 0, maxDepth: 5, minAge: minAge, findings: &findings)
        }

        return findings
    }

    // MARK: Private

    private func walk(
        directory: URL,
        depth: Int,
        maxDepth: Int,
        minAge: TimeInterval?,
        findings: inout [ScanFinding]
    ) async {
        guard depth < maxDepth, !Task.isCancelled else { return }

        let fm = FileManager.default
        // Do not skip hidden files — local artifacts are often `.cache`, `.next`, etc.
        guard let contents = try? fm.contentsOfDirectory(
            at: directory,
            includingPropertiesForKeys: [.isDirectoryKey, .contentModificationDateKey, .creationDateKey],
            options: []
        ) else { return }

        for item in contents {
            guard !Task.isCancelled else { return }

            guard let values = try? item.resourceValues(
                forKeys: [.isDirectoryKey, .contentModificationDateKey, .creationDateKey]
            ), values.isDirectory == true else { continue }

            let rawName = item.lastPathComponent
            let name = rawName.lowercased()

            // Dependency trees are never reclaimable free space (still skip walking into them).
            if ScanPolicy.isProjectDependencyDirectory(name) {
                continue
            }

            if ScanPolicy.projectLocalArtifactDirectoryNames.contains(name) {
                // Age gate: skip if too fresh.
                if let minAge {
                    let effectiveDate = ScanPolicy.effectiveAgeDate(from: values)
                    if let date = effectiveDate, Date().timeIntervalSince(date) < minAge { continue }
                }

                let size = FileSystemUtils.directorySize(url: item)
                guard size > 0 else { continue }

                let lastUsed = values.contentModificationDate

                findings.append(ScanFinding(
                    category: category,
                    riskLevel: riskLevel,
                    reason: reason,
                    path: item.path,
                    sizeBytes: size,
                    lastUsed: lastUsed,
                    confidence: confidence
                ))
                // Don't recurse into matched artifact directories.
            } else if !rawName.hasPrefix(".") {
                // Recurse into visible dirs; skip unknown hidden dirs.
                await walk(directory: item, depth: depth + 1, maxDepth: maxDepth, minAge: minAge, findings: &findings)
            }
        }
    }
}
