import Foundation

/// Detects project-**local** build/cache directories (`.cache`, `target`, `.parcel-cache`, …)
/// inside project roots discovered automatically by Spotlight (via `ProjectRootDiscovery`)
/// **plus** any manually configured scan paths (`ProjectScanPathStore`).
///
/// This is the single project-artifact rule (the Phase 5 path-only `ProjectArtifactRule`
/// was unregistered and removed in R0.5 — both rules registered together double-counted
/// every artifact). Manual paths are folded in here so users who configured them keep
/// their coverage.
///
/// Walk strategy:
///   - Descend up to 8 levels below each confirmed root.
///   - Treat a directory whose last component matches a **local** artifact name as a finding
///     (`.cache`, `target`, `__pycache__`, …). **Not** dependency trees (`node_modules`, `.venv`).
///   - Prune descent into matched artifact directories.
///   - Dependency dirs are skipped entirely (not reclaimable).
///   - Hidden directories that are NOT known artifact names are skipped.
///   - Apply a 7-day age gate for all artifact types.
///   - `dist/` and `build/` are flagged `.review`; everything else is `.safe`.
///   - `build`/`dist`/`target` are only reported when git ignores them and tracks nothing inside.
public struct ProjectArtifactsRule: ScanRule {
    public let id = "project-artifacts-v2"
    public let title = "Project Local Build Caches"
    public let reason = "Project-local build/tool cache (regenerated by build tools; not dependency trees)"
    public let category: ScanCategory = .projectArtifacts
    public let riskLevel: RiskLevel = .safe
    public let confidence: Double = 0.93

    private let discovery: ProjectRootDiscovery
    private let pathStore: ProjectScanPathStore
    private let gitInspector: any GitArtifactInspecting

    /// An artifact directory that passed the name and age gates, not yet sized.
    private struct Candidate {
        let url: URL
        let lowercasedName: String
        let lastUsed: Date?
    }

    public init(
        discovery: ProjectRootDiscovery = .shared,
        pathStore: ProjectScanPathStore = .shared,
        gitInspector: any GitArtifactInspecting = SystemGitArtifactInspector()
    ) {
        self.discovery = discovery
        self.pathStore = pathStore
        self.gitInspector = gitInspector
    }

    public func targetDirectories(environment: ScanEnvironment) -> [URL] { [] }
    public func include(fileURL: URL, resourceValues: URLResourceValues) -> Bool { false }

    public func customScan(environment: ScanEnvironment) async -> [ScanFinding]? {
        await discovery.discoverIfNeeded()
        let discovered = await discovery.confirmedRoots()
        // Fold in manually configured scan paths (Phase 5 store), deduplicated by path.
        var seen = Set<String>()
        let roots = (discovered + pathStore.paths.map { URL(fileURLWithPath: $0) })
            .filter { seen.insert($0.standardizedFileURL.path).inserted }
        guard !roots.isEmpty else { return [] }

        let minAge = ScanPolicy.defaultMinimumAgeSeconds(for: category)
        var candidates: [Candidate] = []

        for root in roots {
            if Task.isCancelled { break }
            await walk(directory: root, depth: 0, maxDepth: 8, minAge: minAge, candidates: &candidates)
        }

        let gated = candidates.filter { ScanPolicy.requiresGitIgnoreEvidence($0.url) }.map(\.url)
        let gitStatuses = await gitInspector.statuses(for: gated)
        return candidates
            .filter { ScanPolicy.gitEvidenceAllows(artifact: $0.url, status: gitStatuses[$0.url.path]) }
            .compactMap { makeFinding($0, sizeIndex: environment.sizeIndex) }
    }

    // MARK: Private

    private func walk(
        directory: URL,
        depth: Int,
        maxDepth: Int,
        minAge: TimeInterval?,
        candidates: inout [Candidate]
    ) async {
        guard depth < maxDepth, !Task.isCancelled else { return }

        let fm = FileManager.default
        guard let contents = try? fm.contentsOfDirectory(
            at: directory,
            includingPropertiesForKeys: [.isDirectoryKey, .contentModificationDateKey, .creationDateKey],
            options: []
        ) else { return }

        for item in contents {
            guard !Task.isCancelled else { return }
            guard let values = try? item.resourceValues(
                forKeys: [.isDirectoryKey, .contentModificationDateKey, .creationDateKey]
            ), values.isDirectory == true else { continue }

            let name = item.lastPathComponent
            let lower = name.lowercased()

            // Never treat dependency trees as free space (node_modules, .venv, …).
            // Skip entirely — not reclaimable and no need to walk inside.
            if ScanPolicy.isProjectDependencyDirectory(lower) {
                continue
            }

            if ScanPolicy.projectLocalArtifactDirectoryNames.contains(lower) {
                guard ScanPolicy.hasRequiredSiblingMarker(item) else { continue }
                // Age gate
                if let minAge {
                    let effectiveDate = ScanPolicy.effectiveAgeDate(from: values)
                    if let date = effectiveDate, Date().timeIntervalSince(date) < minAge { continue }
                }

                candidates.append(Candidate(
                    url: item, lowercasedName: lower, lastUsed: values.contentModificationDate
                ))
                // Do not recurse into matched artifact directories.
            } else if !name.hasPrefix(".") {
                // Recurse into visible directories; skip hidden dirs that aren't artifacts.
                await walk(
                    directory: item,
                    depth: depth + 1,
                    maxDepth: maxDepth,
                    minAge: minAge,
                    candidates: &candidates
                )
            }
        }
    }

    private func makeFinding(_ candidate: Candidate, sizeIndex: DirectorySizeIndex) -> ScanFinding? {
        guard !Task.isCancelled else { return nil }
        let size = sizeIndex.directorySize(url: candidate.url)
        guard size > 0 else { return nil }

        let reviewNames: Set<String> = ["dist", "build"]
        let risk: RiskLevel = reviewNames.contains(candidate.lowercasedName) ? .review : .safe
        let reason = risk == .review
            ? "Build output directory — may contain committed release artifacts"
            : reason

        return ScanFinding(
            category: category,
            riskLevel: risk,
            reason: reason,
            path: candidate.url.path,
            sizeBytes: size,
            lastUsed: candidate.lastUsed,
            confidence: confidence
        )
    }
}
